import Head from "next/head";

import React from 'react'

const HeadPart = () => {
  return (
    <Head>
        <title>Statemind Task</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://api.fontshare.com/v2/css?f[]=general-sans@200,500,301,1,300,600,700&display=swap" rel="stylesheet"/>
    </Head>
  )
}

export default HeadPart